Setup markdown editor
Mayank0255/Stackoverflow-Clone pull request #40
Opened 2021-04-02 16:18 UTC by ddsuhaimi

2021-04-03 06:06 UTC, Mayank0255 requested changes

2021-04-03 06:06 UTC, Mayank0255 commented on client/src/services/injectElipsis.js
> +export default injectElipsis;
I think there is a typo in the name `injectElipsis` which should be `injectEllipsis`. Kindly change the file name, the variable name, export name, and wherever imported.

2021-04-03 06:06 UTC, Mayank0255 commented on client/src/components/RichTextEditor/draft.css
> +.DraftEditor-editorContainer,.DraftEditor-root,.public-DraftEditor-content{height:inherit;text-align:initial}.public-DraftEditor-content[contenteditable=true]{-webkit-user-modify:read-write-plaintext
Its in minified format of `css`, I would recommend formatting it properly and then pasting.

For help - https://www.freeformatter.com/css-beautifier.html

2021-04-03 06:07 UTC, Mayank0255 commented
@ddsuhaimi I have requested some small changes on the PR, other than that great work.

2021-04-03 09:15 UTC, ddsuhaimi commented
@Mayank0255 
Updated with the requested changes

2021-04-03 10:53 UTC, Mayank0255 commented
@ddsuhaimi 

Great job man.

I just checked it out and it works fine for the functionalities given but you have forgotten to add __code__ and __hyperlink__ functionality to it. While adding the code one don't forget to look at the ui of original stackoverflow clone.

And one doubt I had is that what is `htmlSubstring` used for with `injectEllipsis`?

2021-04-03 11:26 UTC, Mayank0255 commented
@ddsuhaimi One last thing that don't forget to remove the monospace feature as it's not required

2021-04-04 06:19 UTC, ddsuhaimi commented
@Mayank0255 
For htmlSubstring and injectEllipsis, I used it for post item in the homepage. Normally, you substring the body to show only first 200 characters right?
Since what we have right now is a string of html, I can't simply do body.substring(200), so htmlSubstring comes to play. What it does is that it will extract the first 200 character without touching the html tag (so we wont lose any formatting). I then created injectEllipsis to inject ellipsis at the end of that substring. If I dont do that, when it happen to cut off in the middle of the word, it looks weird.

For the other 2, the converter library still having an open issues for code block (https://github.com/HubSpot/draft-convert/issues/182) and I'll see how to implement the link since it doesn't come by default in draft.js

2021-04-04 07:14 UTC, Mayank0255 commented
> For htmlSubstring and injectEllipsis, I used it for post item in the homepage. Normally, you substring the body to show only first 200 characters right?

Yes, good work 👍🏽 

> I'll see how to implement the link since it doesn't come by default in draft.js

Sure, do that please and work on the code block thing and removing the monospace too while you are at it.

2021-04-06 07:07 UTC, Mayank0255 commented
@ddsuhaimi 

What's the progress on this?

2021-04-08 02:44 UTC, ddsuhaimi commented
@ddsuhaimi 

Sorry, it is probably gonna take a while. I've been kinda busy lately. I'll develop this in the weekend.

2021-04-08 17:00 UTC, Mayank0255 commented
@ddsuhaimi Sure

2021-04-13 12:01 UTC, Mayank0255 commented
@ddsuhaimi Are you facing any kind of problem somewhere?

2021-04-16 06:57 UTC, Mayank0255 commented
@ddsuhaimi Are you facing any kind of problem somewhere?

2021-04-16 09:06 UTC, ddsuhaimi commented
@Mayank0255 

Hi, sorry it took a while. Turns out, the issue is on 'draft-convert' library itself. It just can't convert code block to its corresponding html (and it is actually an open issue in its repo and still hasn't been resolved). So, there is pretty much no use of having code block in the editor when we can't convert it. This is also the case for link.

2021-04-16 09:32 UTC, Mayank0255 commented
@ddsuhaimi 

Okay, I see

Here's an answer for draftjs to html conversion by the author himself - [Here](https://stackoverflow.com/questions/35884112/draftjs-how-to-initiate-an-editor-with-content/36007299#36007299)

In which the author has recommended to use the libraries listed over there as it's officially built by them and for a running example you can see [this](https://react-rte.org/demo) and the repository to which is listed [here](https://github.com/sstur/react-rte)

In the demo shown __code block__ is specifically implemented also. The link to the package repo is [here](https://github.com/sstur/draft-js-utils)

I hope this solves the issue and if not then let me know.

I know this can be tiring to find out the solution but till know you have done a marvelous job so it won't hurt to finish it off perfectly too. It might seem a big task of replacing the draft-convert with this but it would take hardly and hour after figuring out the approach and for which I am here.

P.S. - I am thinking of integrating docusaurus to the backend in which along with the API, a blog page would also be there in which news would come out referring the contributors and congratulating them and explaining about the contribution to the project. This is just to tell you that the contribution won't be in vain.

2021-04-16 11:42 UTC, ddsuhaimi commented
@Mayank0255 

so is it okay if instead of using pure draft-js with draft-convert, we use react-rte? which i think, under the hood, is draft-js?

2021-04-16 11:56 UTC, Mayank0255 commented
@ddsuhaimi Sure, go ahead

As long as it satisfies our needs, its fine

2021-04-18 14:56 UTC, Mayank0255 reviewed
@ddsuhaimi 

The code looks pretty much fine, so for better review and my convenience could you add two screenshots?
1. of the editor with information written in it while applying most of the essential features, like bold, italics, underline, code block, lists, hyperlinks, etc.
2. of the rendered output of the same in the Post page of the particular post you added

Would that be fine with you to attach?

2021-04-18 15:22 UTC, ddsuhaimi commented
@Mayank0255 
Sure thing. 

![image](https://user-images.githubusercontent.com/30659198/115150798-30d80700-a094-11eb-9290-e226fa33878b.png)
![image](https://user-images.githubusercontent.com/30659198/115150809-39304200-a094-11eb-8213-ac1decc63edc.png)

2021-04-18 17:26 UTC, Mayank0255 commented
@ddsuhaimi Good job man!!

Thank you for working patiently with me 😄 

Looking forward to more of the contributions from your side

2021-04-18 17:27 UTC, merged